### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by rootDEV2990** [Zubenna/project-enumerables#3]
Hey bro good job looks like its coming along great!!
Here are some notes from the team. 

- Try pattern instead of !pattern.nil? == true
- Try to define parameter passing to method as nil instead of false (my_all?)
- Try to check with conditional is not true with the bang (!=)
- In my_all when block is passed try to yield the item and use unless. (l56)

Great Job!

**Comment by Zubenna** [comment]
Recommended changes have been implemented.
